// GENERATED by scripts/build-hero-frames.mjs — do not edit by hand.
// The homepage scroll-cinematography sequence, built from the client's rendered
// walkthrough frames. Re-run the script to regenerate.
export const HERO_SEQUENCE = {
  "count": 137,
  "width": 1440,
  "height": 812,
  "aspect": 1.7734,
  "dir": "/hero",
  "frame": "frame-",
  "ext": ".webp",
  "pad": 3
} as const
